baseURL = 'https://umgefahren.xyz'
languageCode = 'en-us'
title = "umgefahren's blog"
theme = "PaperMod"
env = "production"
enableRobotsTXT = true

[params]
env = "production"
title = "umgefahren's blog"
description = "Personal blog of umgefahren, a student at ETH ZÃ¼rich, Rust developer and p2p enthusiast."

[params.homeInfoParams]

Title = "Welcome ðŸ‘‹ðŸ˜€"
Content = "Personal blog of umgefahren, a student at ETH ZÃ¼rich, Rust developer and p2p enthusiast."

[minify]
    minifyOutput = true

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/one25fps"

[[params.socialIcons]]
name = "github"
url = "https://github.com/umgefahren"


